#set up properties
PROJECT_ID: qwiklabs-gcp-01-8e343ec0963b

management:
    security:
        enabled: false

server:
    port: ${DEFAULT_PORT:80}

spring:
    application:
        name: app-vision
    cloud:
        config:
            namespace: default
            enabled: true
            fail-fast: false 
            name: Cloud
            label: master
        gcp:
            project-id: ${PROJECT_ID:qwiklabs-gcp-01-8e343ec0963b}
            credentials:
                location: classpath:key.json