#set up properties
PROJECT_ID: qwiklabs-gcp-00-96ff96e16985

management:
    security:
        enabled: false

server:
    port: ${DEFAULT_PORT:80}

spring:
    application:
        name: app-translator